apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-demo
  labels:
    app: api-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-demo
  template:
    metadata:
      labels:
        app: api-demo
    spec:
      containers:
        - name: api-demo
          image: saurabh1988gupta/api-demo
          ports:
            - containerPort: 8080