apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api-service
spec:
  ports:
    - name: port0
      port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    app: api-demo
  type: NodePort
  sessionAffinity: None